<h1>View NFT sale</h1>
<div class="row">
    <div class="col-md-12">
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-2">
                    <img class="img-fluid" src="<?php echo $this->nft->getImageUrl(); ?>" />
                </div>
                <div class="col-md-4">
                    <div class="card-body">
                        <h5 class="card-title"><?php echo $this->nft->getTokenName(); ?> [<?php echo $this->nft->getTokenTicker() ?>]</h5>
                        <form method="post">
                            <input type="hidden" name="sale" value="<?php echo $this->nft->getSale()->getId(); ?>" />
                            <label class="form-label">Price</label>
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" value="<?php echo $this->nft->getSale()->getCostAmount(); ?>" disabled>
                                <span class="input-group-text" id="basic-addon2"><?php echo $this->nft->getSale()->getCostTokenTicker(); ?></span>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Send NFT to:</label>
                                <input type="text" name="tokenReceiver" class="form-control" required placeholder="simpleledger:....">
                            </div>
                            <input type="submit" class="btn btn-primary" name="submit" value="Buy NFT" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>