<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mint toolbox | Shadowkite.io</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">🪴 Mint toolbox</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/mint/index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/mint/collections">My collections</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/mint/parent">Add collection</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/mint/child">Add NFT</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <?php echo $this->content; ?>
</div>
</body>
</html>
